-- =========================
-- UTILISATEUR
-- =========================
CREATE TABLE UTILISATEUR (
  ID NUMBER(10) PRIMARY KEY,
  FULL_NAME VARCHAR2(100) NOT NULL,
  PHONE VARCHAR2(20),
  EMAIL VARCHAR2(100) NOT NULL,
  PASSWORD_HASH VARCHAR2(255) NOT NULL,
  STATUS VARCHAR2(20),
  ROLE VARCHAR2(20) NOT NULL,
  CREATED_AT TIMESTAMP(6),
  UPDATED_AT TIMESTAMP(6),
  CONSTRAINT UQ_UTILISATEUR_EMAIL UNIQUE (EMAIL)
);

-- =========================
-- ADMIN
-- =========================
CREATE TABLE ADMIN (
  ID NUMBER(10) PRIMARY KEY,
  EMAIL VARCHAR2(100) NOT NULL,
  PASSWORD_HASH VARCHAR2(255) NOT NULL,
  NUM_TEL VARCHAR2(20),
  NAMECOMPLET VARCHAR2(100),
  CREATED_AT TIMESTAMP(6),
  UPDATED_AT TIMESTAMP(6),
  CONSTRAINT UQ_ADMIN_EMAIL UNIQUE (EMAIL)
);

-- =========================
-- VEHICULE
-- =========================
CREATE TABLE VEHICULE (
  ID NUMBER(10) PRIMARY KEY,
  MARQUE VARCHAR2(50),
  MODELE VARCHAR2(50),
  IMMATRICULATION VARCHAR2(30),
  CIN VARCHAR2(30),
  ATTEST_DOMIC VARCHAR2(100),
  CARTE_GRISE VARCHAR2(100),
  CREER_LE TIMESTAMP(6),
  UPDATED_AT TIMESTAMP(6),
  CONSTRAINT UQ_VEHICULE_IMMATRICULATION UNIQUE (IMMATRICULATION)
);

-- =========================
-- CLIENT (inherits UTILISATEUR)
-- =========================
CREATE TABLE CLIENT (
  ID NUMBER(10) PRIMARY KEY,
  CONSTRAINT FK_CLIENT_UTILISATEUR FOREIGN KEY (ID) REFERENCES UTILISATEUR(ID)
);

-- =========================
-- ADRESSE
-- =========================
CREATE TABLE ADRESSE (
  ID NUMBER(10) PRIMARY KEY,
  UTILISATEUR_ID NUMBER(10),
  CONSTRAINT FK_ADRESSE_UTILISATEUR FOREIGN KEY (UTILISATEUR_ID) REFERENCES UTILISATEUR(ID),
  CONSTRAINT UQ_ADRESSE_UTILISATEUR UNIQUE (UTILISATEUR_ID)
);

-- =========================
-- COURIER
-- =========================
CREATE TABLE COURIER (
  ID NUMBER(10) PRIMARY KEY,
  ID_VEHICULE NUMBER(10),
  DISPONIBLE NUMBER(1),
  RATING_AVG NUMBER(3,2),
  CONSTRAINT FK_COURIER_UTILISATEUR FOREIGN KEY (ID) REFERENCES UTILISATEUR(ID),
  CONSTRAINT FK_COURIER_VEHICULE FOREIGN KEY (ID_VEHICULE) REFERENCES VEHICULE(ID)
);

-- =========================
-- ORDRE
-- =========================
CREATE TABLE ORDRE (
  ID NUMBER(10) PRIMARY KEY,
  ADDRESS_ID NUMBER(10),
  SERVICE_TYPE VARCHAR2(50) NOT NULL,
  PROGRAMME_LE TIMESTAMP(6) NOT NULL,
  STATUT VARCHAR2(30),
  PRIX_TOTAL NUMBER(10,2) NOT NULL,
  FRAIS_PLATEFORME NUMBER(10,2) NOT NULL,
  PROFIT_COURIER NUMBER(10,2) NOT NULL,
  CREER_LE TIMESTAMP(6),
  UPDATED_AT TIMESTAMP(6),
  ID_CLIENT NUMBER(10),
  ID_PROVIDER NUMBER(10),
  CONSTRAINT FK_ORDRE_ADRESSE FOREIGN KEY (ADDRESS_ID) REFERENCES ADRESSE(ID),
  CONSTRAINT FK_ORDRE_CLIENT FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID),
  CONSTRAINT FK_ORDRE_PROVIDER FOREIGN KEY (ID_PROVIDER) REFERENCES COURIER(ID)
);

-- =========================
-- COMMISSION
-- =========================
CREATE TABLE COMMISSION (
  ID NUMBER(10) PRIMARY KEY,
  ID_ORDRE NUMBER(10),
  CONSTRAINT FK_COMMISSION_ORDRE FOREIGN KEY (ID_ORDRE) REFERENCES ORDRE(ID),
  CONSTRAINT UQ_COMMISSION_ID_ORDRE UNIQUE (ID_ORDRE)
);

-- =========================
-- PAIEMENT
-- =========================
CREATE TABLE PAIEMENT (
  ID NUMBER(10) PRIMARY KEY,
  METHODE_PAIEMENT VARCHAR2(50),
  ID_PAIEMENT_PAYPAL VARCHAR2(100),
  MONTANT NUMBER(10,2) NOT NULL,
  STATUT VARCHAR2(20),
  CREER_LE TIMESTAMP(6),
  UPDATED_AT TIMESTAMP(6),
  ID_ORDRE NUMBER(10),
  CONSTRAINT FK_PAIEMENT_ORDRE FOREIGN KEY (ID_ORDRE) REFERENCES ORDRE(ID),
  CONSTRAINT UQ_PAIEMENT_ID_ORDRE UNIQUE (ID_ORDRE)
);

-- =========================
-- PAYMENTCOURIER
-- =========================
CREATE TABLE PAYMENTCOURIER (
  ID NUMBER(10) PRIMARY KEY,
  MONTANT NUMBER(10,2) NOT NULL,
  PAYER_LE TIMESTAMP(6),
  STATUT VARCHAR2(20),
  CREER_LE TIMESTAMP(6),
  UPDATED_AT TIMESTAMP(6),
  ID_COURIER NUMBER(10),
  ID_COMMISSION NUMBER(10),
  CONSTRAINT FK_PAYMENTCOURIER_COURIER FOREIGN KEY (ID_COURIER) REFERENCES COURIER(ID),
  CONSTRAINT FK_PAYMENTCOURIER_COMMISSION FOREIGN KEY (ID_COMMISSION) REFERENCES COMMISSION(ID)
);

-- =========================
-- SERVICECOURIER
-- =========================
CREATE TABLE SERVICECOURIER (
  ID NUMBER(10) PRIMARY KEY,
  TYPE_SERVICE VARCHAR2(50) NOT NULL,
  PRIX NUMBER(10,2) NOT NULL,
  DESCRIPTION CLOB,
  ID_COURIER NUMBER(10),
  CREATED_AT TIMESTAMP(6),
  UPDATED_AT TIMESTAMP(6),
  CONSTRAINT FK_SERVICE_COURIER FOREIGN KEY (ID_COURIER) REFERENCES COURIER(ID)
);

-- =========================
-- COMMENTAIRE
-- =========================
CREATE TABLE COMMENTAIRE (
  ID NUMBER(10) PRIMARY KEY,
  ID_CLIENT NUMBER(10),
  ID_COURIER NUMBER(10),
  ID_ORDRE NUMBER(10),
  NOTE NUMBER(2),
  CONTENU CLOB,
  CONSTRAINT FK_COMMENTAIRE_CLIENT FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID),
  CONSTRAINT FK_COMMENTAIRE_COURIER FOREIGN KEY (ID_COURIER) REFERENCES COURIER(ID),
  CONSTRAINT FK_COMMENTAIRE_ORDRE FOREIGN KEY (ID_ORDRE) REFERENCES ORDRE(ID),
  CONSTRAINT UQ_COMMENTAIRE_ID_ORDRE UNIQUE (ID_ORDRE)
);